/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "clock_2.h"
#include "isr_spd.h"
#include "Hall_Error.h"
#include "PWM_Drive.h"
#include "isr_pwm.h"
#include "PWMCL.h"
#include "PWMCL_aliases.h"
#include "PWMBL.h"
#include "PWMBL_aliases.h"
#include "PWMAL.h"
#include "PWMAL_aliases.h"
#include "PWMCH.h"
#include "PWMCH_aliases.h"
#include "PWMBH.h"
#include "PWMBH_aliases.h"
#include "PWMAH.h"
#include "PWMAH_aliases.h"
#include "Hall3.h"
#include "Hall3_aliases.h"
#include "Hall2.h"
#include "Hall2_aliases.h"
#include "Hall1.h"
#include "Hall1_aliases.h"
#include "CtrlReg_Dir.h"
#include "CtrlReg_PWMOut.h"
#include "clock_1.h"
#include "STATUS_LED.h"
#include "STATUS_LED_aliases.h"
#include "UART_BCP.h"
#include "UART_BCP_SPI_UART.h"
#include "UART_BCP_PINS.h"
#include "UART_BCP_SPI_UART_PVT.h"
#include "UART_BCP_PVT.h"
#include "UART_BCP_BOOT.h"
#include "SW2.h"
#include "SW2_aliases.h"
#include "ADC_SAR_Seq_1.h"
#include "IDAC_Iref.h"
#include "Pin_Ibus.h"
#include "Pin_Ibus_aliases.h"
#include "Pin_Iref.h"
#include "Pin_Iref_aliases.h"
#include "LPComp_OC.h"
#include "isr_oc.h"
#include "Vbus.h"
#include "Vbus_aliases.h"
#include "Vrpm.h"
#include "Vrpm_aliases.h"
#include "Counter_Spd.h"
#include "isr_timeMeasurementForSpeed.h"
#include "Timer_1.h"
#include "UART_BCP_SCBCLK.h"
#include "UART_BCP_tx.h"
#include "UART_BCP_tx_aliases.h"
#include "UART_BCP_rx.h"
#include "UART_BCP_rx_aliases.h"
#include "ADC_SAR_Seq_1_IRQ.h"
#include "ADC_SAR_Seq_1_intClock.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

